/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewJornalista;

import com.devleague.portalnoticias.Controller.Noticia.UpdateNoticiaController;
import com.devleague.portalnoticias.Model.Jornalista;
import com.devleague.portalnoticias.Model.Noticia;
import com.devleague.portalnoticias.View.Components.DialogoMsg;

/**
 *
 * @author Fnatic
 */
public class AtualizarNoticiaFrame extends javax.swing.JFrame {
    public Noticia noticia;
    public Jornalista jornalista;
    /**
     * Creates new form CriarNoticiaFrame
     */
    public AtualizarNoticiaFrame(Jornalista jornalista, Noticia noticia) {
        this.noticia = noticia;
        this.jornalista = jornalista;
        initComponents();
        tituloNoticia.setText(noticia.getTitulo());
        conteudoNoticia.setText(noticia.getConteudo());
        motivoReprovada.setText(noticia.getMotivoReprovada());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tituloNoticia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudoNoticia = new javax.swing.JTextArea();
        salvarNoticiaButtom = new javax.swing.JButton();
        cancelarCriarNoticiaButton = new javax.swing.JButton();
        motivoReprovada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atualizar Noticia");

        tituloNoticia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloNoticia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        conteudoNoticia.setColumns(20);
        conteudoNoticia.setRows(5);
        jScrollPane1.setViewportView(conteudoNoticia);

        salvarNoticiaButtom.setText("Salvar");
        salvarNoticiaButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarNoticiaButtomActionPerformed(evt);
            }
        });

        cancelarCriarNoticiaButton.setText("Cancelar");
        cancelarCriarNoticiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCriarNoticiaButtonActionPerformed(evt);
            }
        });

        motivoReprovada.setText("jLabel2");
        motivoReprovada.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tituloNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(motivoReprovada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cancelarCriarNoticiaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarNoticiaButtom)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvarNoticiaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelarCriarNoticiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addComponent(motivoReprovada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarCriarNoticiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCriarNoticiaButtonActionPerformed
        this.setVisible(false);
        new JornalistaFrame(this.jornalista).setVisible(true);

    }//GEN-LAST:event_cancelarCriarNoticiaButtonActionPerformed

    private void salvarNoticiaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarNoticiaButtomActionPerformed
        noticia.setConteudo(conteudoNoticia.getText());
        noticia.setCriada(true);
        try{
            UpdateNoticiaController.update(noticia);
            this.setVisible(false);
            new JornalistaFrame(this.jornalista).setVisible(true);
            new DialogoMsg("Noticia criada com sucesso!");
        }catch (Exception e){
            new DialogoMsg(e.toString());
        }

    }//GEN-LAST:event_salvarNoticiaButtomActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCriarNoticiaButton;
    private javax.swing.JTextArea conteudoNoticia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel motivoReprovada;
    private javax.swing.JButton salvarNoticiaButtom;
    private javax.swing.JLabel tituloNoticia;
    // End of variables declaration//GEN-END:variables
}
