/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewJornalista;

import com.devleague.portalnoticias.Controller.Chefe.GetChefeController;
import com.devleague.portalnoticias.Controller.Noticia.GetNoticiaController;
import com.devleague.portalnoticias.DB.DB;
import com.devleague.portalnoticias.Model.Chefe;
import com.devleague.portalnoticias.Model.Jornalista;
import com.devleague.portalnoticias.Model.Noticia;
import com.devleague.portalnoticias.View.Components.DialogoMsg;
import com.devleague.portalnoticias.View.ViewChefe.Table.ListaChefesTable;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.UUID;

/**
 *
 * @author Fnatic
 */
public class JornalistaFrame extends javax.swing.JFrame {

    private Jornalista jornalista;
    /**
     * Creates new form JornalistaFrame
     */
    public JornalistaFrame(Jornalista jornalista) {

        this.jornalista = jornalista;
        initComponents();
        criarNoticiaList();
        noticiasRejeitadas();
                
    }

    private void noticiasRejeitadas() {
        ArrayList<Noticia> chefes = GetNoticiaController.getReproved(jornalista.getId());
        NoticiaToCreateTable tm = new NoticiaToCreateTable(chefes);


        tableNoticiaRejeitada = new JTable(tm);
        tableNoticiaRejeitada.getColumnModel().getColumn(0).setPreferredWidth(1);

        jScrollPane2.setViewportView(tableNoticiaRejeitada);
    }

    public void criarNoticiaList(){

        ArrayList<Noticia> chefes = GetNoticiaController.getToCreate(jornalista.getId());
        NoticiaToCreateTable tm = new NoticiaToCreateTable(chefes);


        tableCriacaoNoticias = new JTable(tm);
        tableCriacaoNoticias.getColumnModel().getColumn(0).setPreferredWidth(1);
        jScrollPane1.setViewportView(tableCriacaoNoticias);
        tableCriacaoNoticias.addMouseListener(
            new MouseAdapter() {
                public void mouseClicked (MouseEvent me) {
                    int row = tableCriacaoNoticias.rowAtPoint(me.getPoint());
                    if (me.getClickCount() == 2 && tableCriacaoNoticias.getSelectedRow()== row) {
                        criarNociciaFrame(GetNoticiaController.get((UUID)tableCriacaoNoticias.getValueAt(row, 0)));

                    }
                }
            }
        );
    }
    public  void criarNociciaFrame(Noticia noticia){
        CriarNoticiaFrame criarNoticiaFrame = new CriarNoticiaFrame(this.jornalista, noticia);
        criarNoticiaFrame.setVisible(true);
        this.setVisible(false);
    }
    public  void corrigirNociciaFrame(Noticia noticia){
        AtualizarNoticiaFrame atualizarNoticiaFrame = new AtualizarNoticiaFrame(this.jornalista, noticia);
        atualizarNoticiaFrame.setVisible(true);
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCriacaoNoticias = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        criarNoticiaButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNoticiaRejeitada = new javax.swing.JTable();
        atualizarNoticia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("tt");

        tableCriacaoNoticias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCriacaoNoticias);

        criarNoticiaButton.setLabel("Criar Noticia");
        criarNoticiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarNoticiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criarNoticiaButton)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criarNoticiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Criação de Noticias", jPanel1);

        tableNoticiaRejeitada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableNoticiaRejeitada);

        atualizarNoticia.setText("Corrigir Noticia");
        atualizarNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarNoticiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizarNoticia)
                .addGap(0, 119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(atualizarNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Noticias Rejeitadas", jPanel2);

        jButton1.setLabel("<--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarNoticiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarNoticiaButtonActionPerformed
        if (tableCriacaoNoticias.getSelectedRow() != -1) {
            criarNociciaFrame(GetNoticiaController.get((UUID) tableCriacaoNoticias.getValueAt(tableCriacaoNoticias.getSelectedRow(), 0)));
        }else{
            new DialogoMsg("Nenhuma noticia selecionada");
        }
    }//GEN-LAST:event_criarNoticiaButtonActionPerformed

    private void atualizarNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarNoticiaActionPerformed
        if (tableNoticiaRejeitada.getSelectedRow() != -1) {
            corrigirNociciaFrame(GetNoticiaController.get((UUID) tableNoticiaRejeitada.getValueAt(tableNoticiaRejeitada.getSelectedRow(), 0)));
        }else{
            new DialogoMsg("Nenhuma noticia selecionada");
        }
    }//GEN-LAST:event_atualizarNoticiaActionPerformed


    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarNoticia;
    private javax.swing.JToggleButton criarNoticiaButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableCriacaoNoticias;
    private javax.swing.JTable tableNoticiaRejeitada;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
