/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewCliente;

import com.devleague.portalnoticias.Controller.Anuncio.GetAnuncioController;
import com.devleague.portalnoticias.Controller.Categoria.GetCategoriaController;
import com.devleague.portalnoticias.Controller.Cliente.GetClienteController;
import com.devleague.portalnoticias.Controller.Comentario.CreateComentarioController;
import com.devleague.portalnoticias.Controller.Comentario.GetComentarioController;
import com.devleague.portalnoticias.Controller.Jornalista.GetJornalistaController;
import com.devleague.portalnoticias.Controller.Noticia.UpdateNoticiaController;
import com.devleague.portalnoticias.Model.Anuncio;
import com.devleague.portalnoticias.Model.Cliente;
import com.devleague.portalnoticias.Model.Comentario;
import com.devleague.portalnoticias.Model.Noticia;
import com.devleague.portalnoticias.View.Components.DialogoMsg;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author david
 */
public class VisualizarNoticiaFisica extends javax.swing.JFrame {
    public Cliente cliente;
    public String noticiaImprimir;
    /**
     * Creates new form VisualizarNoticia
     */
    Noticia noticiaAtual = null;
    public VisualizarNoticiaFisica(Noticia noticia, Cliente cliente) {
        this.cliente = cliente;
        initComponents();
        this.noticiaAtual = noticia;
        setDadosIniciais();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudo = new javax.swing.JTextArea();
        imprimir = new javax.swing.JButton();
        autor = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        anuncio = new javax.swing.JTextArea();
        javax.swing.JLabel anuncios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Autor:");

        jLabel2.setText("Titulo:");

        jLabel3.setText("Categoria:");

        jLabel4.setText("Data");

        jLabel5.setText("Conteudo:");

        conteudo.setColumns(20);
        conteudo.setRows(5);
        conteudo.setEnabled(false);
        jScrollPane1.setViewportView(conteudo);

        imprimir.setText("Imprimir");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    imprimirActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        anuncio.setColumns(20);
        anuncio.setRows(5);
        anuncio.setEnabled(false);
        jScrollPane4.setViewportView(anuncio);

        anuncios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anuncios.setText("Anuncios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                                    .addComponent(categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addComponent(anuncios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imprimir)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(autor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anuncios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imprimir)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_imprimirActionPerformed

        noticiaImprimir ="Titulo: "+ noticiaAtual.getTitulo();
        noticiaImprimir += "\nAutor: " + GetJornalistaController.get( noticiaAtual.getAuthor()).getNome();
        noticiaImprimir += "\nCategoria: " + GetCategoriaController.get( noticiaAtual.getCategoria()).getNome();
        noticiaImprimir += "\nData: " + noticiaAtual.getData();
        noticiaImprimir += "\nConteudo: \n " + noticiaAtual.getConteudo();
        noticiaImprimir+= "\n\n\n";
        noticiaImprimir+= "Anuncios: ";
        noticiaAtual.getAnuncios().forEach(anun -> {

            Date date = new Date();
            Anuncio an = GetAnuncioController.get(anun);

            String[] data = an.getFimVisualizacao().split("/");
            if(date.getYear() <= Integer.getInteger(data[2])){
                if(date.getMonth() <= Integer.getInteger(data[1])){
                    if(date.getDay() <= Integer.getInteger(data[0])){
                        noticiaImprimir += "\n\n" + an.getConteudo();
                        an.setExemplaresEntregues(an.getExemplaresEntregues()+1);
                    }
                }
            }
        });
        FileWriter wNoticias = new FileWriter("noticia.txt");
        wNoticias.write(noticiaImprimir);
        wNoticias.close();
        new DialogoMsg("Imprimido com sucesso!");

    }//GEN-LAST:event_imprimirActionPerformed
    public void setDadosIniciais(){
        titulo.setText(noticiaAtual.getTitulo());
        conteudo.setText(noticiaAtual.getConteudo());
        try {
            autor.setText(GetJornalistaController.get(noticiaAtual.getAtribuidoA()).getNome());
            categoria.setText(GetCategoriaController.get(noticiaAtual.getCategoria()).getNome());
            data.setText(noticiaAtual.getData());

            noticiaAtual.getAnuncios().forEach(anun -> {
                Date date = new Date();

                Anuncio an = GetAnuncioController.get(anun);
                String[] data = an.getFimVisualizacao().split("/");
                if(date.getYear() <= Integer.getInteger(data[2])){
                    if(date.getMonth() <= Integer.getInteger(data[1])){
                        if(date.getDay() <= Integer.getInteger(data[0])){
                            anuncio.setText(anuncio.getText() + "\n\n" + an.getConteudo());
                        }
                    }
                }
            });
        }catch (Exception e){
            new DialogoMsg("Não foi possivel encontrar os dados da noticia!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anuncio;
    private javax.swing.JLabel autor;
    private javax.swing.JLabel categoria;
    private javax.swing.JTextArea conteudo;
    private javax.swing.JLabel data;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
