/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewEditor;

import com.devleague.portalnoticias.Controller.Noticia.UpdateNoticiaController;
import com.devleague.portalnoticias.Model.Editor;
import com.devleague.portalnoticias.Model.Jornalista;
import com.devleague.portalnoticias.Model.Noticia;
import com.devleague.portalnoticias.View.Components.DialogoMsg;
import com.devleague.portalnoticias.View.ViewJornalista.JornalistaFrame;

/**
 *
 * @author Fnatic
 */
public class EditarNoticiaFrame extends javax.swing.JFrame {
    public Noticia noticia;
    public Editor editor;
    /**
     * Creates new form EditarNoticiaFrame
     */
    public EditarNoticiaFrame(Editor editor, Noticia noticia) {
        this.noticia = noticia;
        this.editor = editor;
        initComponents();
        tituloNoticia.setText(noticia.getTitulo());
        conteudoNoticia.setText(noticia.getConteudo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tituloNoticia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        conteudoNoticia = new javax.swing.JTextArea();
        salvarNoticiaButtom = new javax.swing.JButton();
        cancelarEditarNoticiaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Noticia");

        tituloNoticia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tituloNoticia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        conteudoNoticia.setColumns(20);
        conteudoNoticia.setRows(5);
        jScrollPane1.setViewportView(conteudoNoticia);

        salvarNoticiaButtom.setText("Salvar");
        salvarNoticiaButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarNoticiaButtomActionPerformed(evt);
            }
        });

        cancelarEditarNoticiaButton.setText("Cancelar");
        cancelarEditarNoticiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEditarNoticiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tituloNoticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelarEditarNoticiaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarNoticiaButtom)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarNoticiaButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarEditarNoticiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarEditarNoticiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEditarNoticiaButtonActionPerformed
        this.setVisible(false);
        new PageEditor(this.editor).setVisible(true);

    }//GEN-LAST:event_cancelarEditarNoticiaButtonActionPerformed

    private void salvarNoticiaButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarNoticiaButtomActionPerformed
        noticia.setConteudo(conteudoNoticia.getText());
        noticia.setEditada(true);
        try{
            UpdateNoticiaController.update(noticia);
            this.setVisible(false);
            new PageEditor(this.editor).setVisible(true);
            new DialogoMsg("Noticia editada com sucesso!");
        }catch (Exception e){
            new DialogoMsg(e.toString());
        }

    }//GEN-LAST:event_salvarNoticiaButtomActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarEditarNoticiaButton;
    private javax.swing.JTextArea conteudoNoticia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salvarNoticiaButtom;
    private javax.swing.JLabel tituloNoticia;
    // End of variables declaration//GEN-END:variables
}
