/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewEditor;

import com.devleague.portalnoticias.Controller.Editor.CreateEditorController;
import com.devleague.portalnoticias.Controller.Editor.DeleteEditorController;
import com.devleague.portalnoticias.Controller.Editor.GetEditorController;
import com.devleague.portalnoticias.Model.Editor;
import com.devleague.portalnoticias.View.Acesso;
import com.devleague.portalnoticias.View.Components.DialogoMsg;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 *
 * @author Fnatic
 */
public class ListaEditor extends JFrame {


    /**
     * Creates new form ListaEditores
     */
    public ListaEditor()  {

        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new JDialog();
        jDialog2 = new JDialog();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        listaEditores = new JTable();
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        nomeEditor = new JTextField();
        salarioEditor = new JTextField();
        butaoCriarEditor = new JButton();
        excluirEditor = new JButton();
        logarEditor = new JButton();
        jButton1 = new JButton();

        GroupLayout jDialog1Layout = new GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        GroupLayout jDialog2Layout = new GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Selecione o Editor para entrar");

        listaEditores.setAutoCreateColumnsFromModel(false);
        listaEditores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaEditores);

        jPanel1.setMaximumSize(new Dimension(300, 65000));

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Criar Novo Editor");

        jLabel3.setText("Nome: ");

        jLabel4.setText("Salario:");

        salarioEditor.setToolTipText("");

        butaoCriarEditor.setText("Registrar");
        butaoCriarEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoCriarEditorMouseClicked(evt);
            }
        });

        excluirEditor.setText("Excluir Editor");
        excluirEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirEditorMouseClicked(evt);
            }
        });

        logarEditor.setText("Logar Editor");
        logarEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logarEditorMouseClicked(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(nomeEditor)
                            .addComponent(salarioEditor)))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butaoCriarEditor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirEditor, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logarEditor, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeEditor, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salarioEditor, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(butaoCriarEditor, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(logarEditor, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirEditor, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("<--");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 532, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoCriarEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoCriarEditorMouseClicked

        if(nomeEditor.getText().length() < 3){
            new DialogoMsg("Nome do Editor precisa ter ao menos 3 caracteres");
            return;
        }
        Pattern pattern = Pattern.compile("\\d+.\\d+");

        if(!pattern.matcher(salarioEditor.getText()).matches()){
            new DialogoMsg("Salario do editor invalido");
            return;
        }
        try{
            Editor editor = new Editor();
            editor.setNome(nomeEditor.getText());
            editor.setSalario(Float.parseFloat(salarioEditor.getText()));
            if(CreateEditorController.add(editor)){
                table();
            }else{
                new DialogoMsg("Não foi possivel Criar o editor");
                return;
            }
        }catch (Exception e){
            new DialogoMsg("Salario do editor invalido");
            return;
        }





    }//GEN-LAST:event_butaoCriarEditorMouseClicked

    private void excluirEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirEditorMouseClicked
        try {
            Editor editor = GetEditorController.get( (UUID) listaEditores.getValueAt(listaEditores.getSelectedRow(), 0));
            if (editor != null) {
                if (DeleteEditorController.delete(editor)) {
                    table();
                } else {
                    new DialogoMsg("Não foi possivel excluir o editor!");
                }
            } else {
                new DialogoMsg("Editor não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum Editor selecionado!");
        }
    }//GEN-LAST:event_excluirEditorMouseClicked

    private void logarEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logarEditorMouseClicked
        try {
            Editor editor = GetEditorController.get((UUID) listaEditores.getValueAt(listaEditores.getSelectedRow(), 0));
            if (editor != null) {
                new PageEditor(editor).setVisible(true);
                this.setVisible(false);

            } else {
                new DialogoMsg("Editor não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum Editor selecionado!");
        }
    }//GEN-LAST:event_logarEditorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new Acesso().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed



    private void table(){

        ArrayList<Editor> editors = GetEditorController.getAll();


        ListaEditoresTable tm = new ListaEditoresTable(editors);


        listaEditores = new JTable(tm);
        listaEditores.getColumnModel().getColumn(0).setPreferredWidth(200);
        jScrollPane1.setViewportView(listaEditores);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton butaoCriarEditor;
    private JButton excluirEditor;
    private JButton jButton1;
    private JDialog jDialog1;
    private JDialog jDialog2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTable listaEditores;
    private JButton logarEditor;
    private JTextField nomeEditor;
    private JTextField salarioEditor;
    // End of variables declaration//GEN-END:variables
}
