/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewMediador;

import com.devleague.portalnoticias.Controller.Comentario.CreateComentarioController;
import com.devleague.portalnoticias.Controller.Comentario.GetComentarioController;
import com.devleague.portalnoticias.Controller.Comentario.UpdateComentarioController;
import com.devleague.portalnoticias.Model.Comentario;
import com.devleague.portalnoticias.View.Components.DialogoMsg;
import com.devleague.portalnoticias.View.ViewMediador.Table.ListaMediadorTable;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JTable;

/**
 *
 * @author david
 */
public class PageMediador extends javax.swing.JFrame {

    /**
     * Creates new form PageMediador
     */
    public PageMediador() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMediador = new javax.swing.JTable();
        aprovar = new javax.swing.JButton();
        reprovar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mediador");

        tabelaMediador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "usuario", "comentario"
            }
        ));
        jScrollPane1.setViewportView(tabelaMediador);

        aprovar.setText("Aprovar");
        aprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aprovarMouseClicked(evt);
            }
        });

        reprovar.setText("Reprovar");
        reprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reprovarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reprovar)
                        .addGap(18, 18, 18)
                        .addComponent(aprovar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprovar)
                    .addComponent(reprovar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aprovarMouseClicked
        // TODO add your handling code here:
            UUID id = (UUID)tabelaMediador.getValueAt(tabelaMediador.getSelectedRow(), 0);
            Comentario comentarioAtual =  GetComentarioController.get(id);
            comentarioAtual.setAprovada(true);
            UpdateComentarioController.update(comentarioAtual);
            new DialogoMsg("Comentario aprovado com sucesso!");
            table();

        
    }//GEN-LAST:event_aprovarMouseClicked

    private void reprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reprovarMouseClicked
        // TODO add your handling code here:
            UUID id = (UUID)tabelaMediador.getValueAt(tabelaMediador.getSelectedRow(), 0);
            Comentario comentarioAtual =  GetComentarioController.get(id);
            comentarioAtual.setAprovada(false);
            UpdateComentarioController.update(comentarioAtual);
            new DialogoMsg("Comentario reprovado com sucesso!");
            table();
        
    }//GEN-LAST:event_reprovarMouseClicked

    private void table(){
//        Aqui deve ser substituido por um controlador

//        CreateComentarioController.add(helperCreateComentario());
        
        ArrayList<Comentario> Comentarios = GetComentarioController.getAll();
        ListaMediadorTable tm = new ListaMediadorTable(Comentarios);
        tabelaMediador = new JTable(tm);
        jScrollPane1.setViewportView(tabelaMediador);
    }
    
    public Comentario helperCreateComentario(){
        String conteudo = "Da dez para gente, fernanda. Pelo amor de deus!!";
        Comentario mockComentario = new Comentario();
        mockComentario.setConteudo(conteudo);
        
        return mockComentario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprovar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reprovar;
    private javax.swing.JTable tabelaMediador;
    // End of variables declaration//GEN-END:variables
}
