/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewMediador;

import com.devleague.portalnoticias.Controller.Mediador.CreateMediadorController;
import com.devleague.portalnoticias.Controller.Mediador.DeleteMediadorController;
import com.devleague.portalnoticias.Controller.Mediador.GetMediadorController;
import com.devleague.portalnoticias.Model.Comentario;
import com.devleague.portalnoticias.Model.Mediador;
import com.devleague.portalnoticias.View.Acesso;
import com.devleague.portalnoticias.View.Components.DialogoMsg;
import com.devleague.portalnoticias.View.ViewMediador.MediadorFrame;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Pattern;
import javax.swing.JTable;

/**
 *
 * @author david
 */
public class PageMediador extends javax.swing.JFrame {

    /**
     * Creates new form PageMediador
     */
    public PageMediador() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMediadores = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeMediador = new javax.swing.JTextField();
        salarioMediador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        butaoCriarMediador = new javax.swing.JButton();
        logarMediador = new javax.swing.JButton();
        excluirMediador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaMediadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listaMediadores);

        back.setText("<--");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione o Mediador para entrar");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Criar Novo Mediador");

        salarioMediador.setToolTipText("");

        jLabel7.setText("Salario:");

        jLabel8.setText("Nome: ");

        butaoCriarMediador.setText("Registrar");
        butaoCriarMediador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoCriarMediadorMouseClicked(evt);
            }
        });

        logarMediador.setText("Logar Mediador");
        logarMediador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logarMediadorMouseClicked(evt);
            }
        });

        excluirMediador.setText("Excluir Mediador");
        excluirMediador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMediadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeMediador)
                                    .addComponent(salarioMediador)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(butaoCriarMediador))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(excluirMediador, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(logarMediador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeMediador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salarioMediador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(butaoCriarMediador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logarMediador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirMediador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
       this.setVisible(false);
       new Acesso().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void butaoCriarMediadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoCriarMediadorMouseClicked
        
        if(nomeMediador.getText().length() < 3){
            new DialogoMsg("Nome do Mediador precisa ter ao menos 3 caracteres");
            return;
        }
        Pattern pattern = Pattern.compile("\\d+.\\d+");

        if(!pattern.matcher(salarioMediador.getText()).matches()){
            new DialogoMsg("Salario do Mediador invalido");
            return;
        }
        try{
            Mediador mediador = new Mediador();
            mediador.setNome(nomeMediador.getText());
            mediador.setSalario(Float.parseFloat(salarioMediador.getText()));
            if(CreateMediadorController.add(mediador)){
                table();
            }else{
                new DialogoMsg("Não foi possivel Criar o Mediador");
                return;
            }
        }catch (Exception e){
            new DialogoMsg("Salario do Mediador invalido");
            return;
        }
 

    }//GEN-LAST:event_butaoCriarMediadorMouseClicked

    private void logarMediadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logarMediadorMouseClicked
        try {
            Mediador mediador = GetMediadorController.get((UUID) listaMediadores.getValueAt(listaMediadores.getSelectedRow(), 0));
            if (mediador != null) {
                new MediadorFrame(mediador).setVisible(true);
                this.setVisible(false);

            } else {
                new DialogoMsg("mediador não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum mediador selecionado!");
        }
    }//GEN-LAST:event_logarMediadorMouseClicked

    private void excluirMediadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMediadorMouseClicked
         try {
            Mediador mediador = GetMediadorController.get( (UUID) listaMediadores.getValueAt(listaMediadores.getSelectedRow(), 0));
            if (mediador != null) {
                if (DeleteMediadorController.delete(mediador)) {
                    table();
                } else {
                    new DialogoMsg("Não foi possivel excluir o Mediador!");
                }
            } else {
                new DialogoMsg("Mediador não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum Mediador selecionado!");
        }
    }//GEN-LAST:event_excluirMediadorMouseClicked

    private void table(){
//        Aqui deve ser substituido por um controlador

//        CreateComentarioController.add(helperCreateComentario());
        
//        ArrayList<Comentario> Comentarios = GetComentarioController.getAll();
//        ListaComentariosTable tm = new ListaComentariosTable(Comentarios);
//        tabelaMediador = new JTable(tm);
//        jScrollPane1.setViewportView(tabelaMediador);
        ArrayList<Mediador> mediadores = GetMediadorController.getAll();
        ListaMediadoresTable tm = new ListaMediadoresTable(mediadores);
        listaMediadores = new JTable(tm);
        jScrollPane1.setViewportView(listaMediadores);

    }
    
    public Comentario helperCreateComentario(){
        String conteudo = "Da dez para gente, fernanda. Pelo amor de deus!!";
        Comentario mockComentario = new Comentario();
        mockComentario.setConteudo(conteudo);
        
        return mockComentario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton butaoCriarJornalista;
    private javax.swing.JButton butaoCriarMediador;
    private javax.swing.JButton excluirJornalista;
    private javax.swing.JButton excluirMediador;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaMediadores;
    private javax.swing.JButton logarJornalista;
    private javax.swing.JButton logarMediador;
    private javax.swing.JTextField nomeJornalista;
    private javax.swing.JTextField nomeMediador;
    private javax.swing.JTextField salarioJornalista;
    private javax.swing.JTextField salarioMediador;
    // End of variables declaration//GEN-END:variables
}
