/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewChefe;

import com.devleague.portalnoticias.Controller.Categoria.CreateCategoriaController;
import com.devleague.portalnoticias.Controller.Categoria.DeleteCategoriaController;
import com.devleague.portalnoticias.Controller.Categoria.GetCategoriaController;
import com.devleague.portalnoticias.Controller.Jornalista.DeleteJornalistaController;
import com.devleague.portalnoticias.Controller.Jornalista.GetJornalistaController;
import com.devleague.portalnoticias.Controller.Noticia.CreateNoticiaController;
import com.devleague.portalnoticias.Controller.Noticia.GetNoticiaController;
import com.devleague.portalnoticias.Controller.Noticia.UpdateNoticiaController;
import com.devleague.portalnoticias.DB.DB;
import com.devleague.portalnoticias.Model.Categoria;
import com.devleague.portalnoticias.Model.Chefe;
import com.devleague.portalnoticias.Model.Jornalista;
import com.devleague.portalnoticias.Model.Noticia;
import com.devleague.portalnoticias.View.Acesso;
import com.devleague.portalnoticias.View.Components.DialogoMsg;
import com.devleague.portalnoticias.View.ViewChefe.Table.*;

import javax.swing.*;
import java.util.ArrayList;
import java.util.UUID;

/**
 *
 * @author david
 */
public class PageChefeRedacao extends javax.swing.JFrame {

    Chefe chefe;
    ArrayList<Jornalista> jornalistas;
    ArrayList<Categoria> categorias;
    /**
     * Creates new form PageChefeRedacao
     */
    public PageChefeRedacao(Chefe chefe) {

        this.chefe = chefe;
        initComponents();
        init();

    }
    private void init(){
        pageAprovar();
        pageAtribuir();
        pageCategoria();



    }
    private void pageAprovar(){
        tableMaterias();
    }
    private void pageAtribuir(){
        this.categorias = GetCategoriaController.getAll();
        this.jornalistas = GetJornalistaController.getAll();
        selectCategoria.removeAllItems();
        selectJornalista.removeAllItems();
        this.jornalistas.forEach(jornalista -> selectJornalista.addItem(jornalista.getNome()));
        this.categorias.forEach(categoria -> selectCategoria.addItem(categoria.getNome()));
    }
    private void pageCategoria(){
        tableCategorias();
    }
    private void tableMaterias(){

        ArrayList<Noticia> noticia = GetNoticiaController.getRevised();
        NoticiasAAprovarTable tm = new NoticiasAAprovarTable(noticia);
        materiasAAprovar = new JTable(tm);
        materiasAAprovar.getColumnModel().getColumn(0).setPreferredWidth(0);
        materiasAAprovar.getColumnModel().getColumn(0).setMaxWidth(0);
        jScrollPane1.setViewportView(materiasAAprovar);


    }
    private void tableCategorias(){

        ArrayList<Categoria> categorias = GetCategoriaController.getAll();
        CategoriasTable tm = new CategoriasTable(categorias);
        tableCategorias = new JTable(tm);
        jScrollPane2.setViewportView(tableCategorias);



    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materiasAAprovar = new javax.swing.JTable();
        visualizarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botaoSalvarAtribuirNoticia = new javax.swing.JButton();
        privadoAtribuirNoticia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tituloAtribuirNoticia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectJornalista = new javax.swing.JComboBox<>();
        selectCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeCategoria = new javax.swing.JTextField();
        btnCriarCategoria = new javax.swing.JButton();
        btnExcluirCategoria = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        materiasAAprovar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "Matéria", "Status"
            }
        ));
        jScrollPane1.setViewportView(materiasAAprovar);

        visualizarButton.setText("Visualizar");
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(visualizarButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(visualizarButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Aprovar Materia", jPanel2);

        botaoSalvarAtribuirNoticia.setText("Salvar");
        botaoSalvarAtribuirNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarAtribuirNoticiaActionPerformed(evt);
            }
        });

        privadoAtribuirNoticia.setText("Privado");
        privadoAtribuirNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privadoAtribuirNoticiaActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo:");

        tituloAtribuirNoticia.setMinimumSize(new java.awt.Dimension(64, 30));
        tituloAtribuirNoticia.setPreferredSize(new java.awt.Dimension(64, 30));

        jLabel2.setText("Jornalista:");

        selectJornalista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectJornalista.setMinimumSize(new java.awt.Dimension(69, 30));
        selectJornalista.setPreferredSize(new java.awt.Dimension(69, 30));
        selectJornalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectJornalistaActionPerformed(evt);
            }
        });

        selectCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectCategoria.setMinimumSize(new java.awt.Dimension(69, 30));
        selectCategoria.setPreferredSize(new java.awt.Dimension(69, 30));
        selectCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria:");

        jButton3.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloAtribuirNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvarAtribuirNoticia))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(privadoAtribuirNoticia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(selectJornalista, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(privadoAtribuirNoticia)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloAtribuirNoticia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectJornalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarAtribuirNoticia)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Atribuir Noticia", jPanel1);

        tableCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCategorias);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Criar Categoria");

        jLabel5.setText("Nome: ");

        btnCriarCategoria.setText("Criar Categoria");
        btnCriarCategoria.setMaximumSize(new java.awt.Dimension(75, 30));
        btnCriarCategoria.setMinimumSize(new java.awt.Dimension(75, 30));
        btnCriarCategoria.setPreferredSize(new java.awt.Dimension(75, 30));
        btnCriarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarCategoriaMouseClicked(evt);
            }
        });

        btnExcluirCategoria.setText("Excluir");
        btnExcluirCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirCategoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCategoria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 77, Short.MAX_VALUE)
                        .addComponent(btnCriarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnExcluirCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCriarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista de Categorias", jPanel3);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bem Vindo ");

        jButton5.setText("<--");
        jButton5.setMaximumSize(new java.awt.Dimension(75, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(75, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void privadoAtribuirNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privadoAtribuirNoticiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privadoAtribuirNoticiaActionPerformed

    private void selectJornalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectJornalistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectJornalistaActionPerformed

    private void selectCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectCategoriaActionPerformed

    private void btnCriarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarCategoriaMouseClicked
        if(nomeCategoria.getText().length() < 3){
            new DialogoMsg("Nome do Jornalista precisa ter ao menos 3 caracteres");
            return;
        }
        Categoria categoria = new Categoria();
        categoria.setNome(nomeCategoria.getText());
        CreateCategoriaController.add( categoria);
        pageCategoria();
        pageAtribuir();
    }//GEN-LAST:event_btnCriarCategoriaMouseClicked

    private void btnExcluirCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirCategoriaMouseClicked
        try {
            Categoria categoria = GetCategoriaController.get( (UUID) tableCategorias.getValueAt(tableCategorias.getSelectedRow(), 0));
            if (categoria != null) {
                if (DeleteCategoriaController.delete( categoria)) {
                    pageCategoria();
                    pageAtribuir();
                } else {
                    new DialogoMsg("Não foi possivel excluir a categoria!");
                }
            } else {
                new DialogoMsg("Categoria não encontrada!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhuma Categoria selecionada!");
        }
    }//GEN-LAST:event_btnExcluirCategoriaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new ListaChefes().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botaoSalvarAtribuirNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarAtribuirNoticiaActionPerformed

        Noticia noticia = new Noticia();
        noticia.setAtribuidoA(jornalistas.get(selectJornalista.getSelectedIndex()).getId());
        noticia.setAuthor(jornalistas.get(selectJornalista.getSelectedIndex()).getId());
        noticia.setAtribuidoPor(chefe.getId());
        noticia.setCategoria(categorias.get(selectCategoria.getSelectedIndex()).getId());
        noticia.setTitulo(tituloAtribuirNoticia.getText());
        noticia.setPrivado(privadoAtribuirNoticia.isSelected());

        try {
            CreateNoticiaController.add(noticia);
            new DialogoMsg("Noticia atribuida com sucesso!");
            tituloAtribuirNoticia.setText("");
            privadoAtribuirNoticia.setSelected(false);
        } catch (Exception e){
            new DialogoMsg(e.toString());
        }
    }//GEN-LAST:event_botaoSalvarAtribuirNoticiaActionPerformed

    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed

        new AprovarNoticia(GetNoticiaController.get((UUID) materiasAAprovar.getValueAt(materiasAAprovar.getSelectedRow(), 0)), chefe).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visualizarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvarAtribuirNoticia;
    private javax.swing.JButton btnCriarCategoria;
    private javax.swing.JButton btnExcluirCategoria;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable materiasAAprovar;
    private javax.swing.JTextField nomeCategoria;
    private javax.swing.JCheckBox privadoAtribuirNoticia;
    private javax.swing.JComboBox<String> selectCategoria;
    private javax.swing.JComboBox<String> selectJornalista;
    private javax.swing.JTable tableCategorias;
    private javax.swing.JTextField tituloAtribuirNoticia;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables
}
