/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devleague.portalnoticias.View.ViewAnuciante;

import com.devleague.portalnoticias.Controller.Anunciante.CreateAnuncianteController;
import com.devleague.portalnoticias.Controller.Anunciante.DeleteAnuncianteController;
import com.devleague.portalnoticias.Controller.Anunciante.GetAnuncianteController;
import com.devleague.portalnoticias.Model.Anunciante;
import com.devleague.portalnoticias.View.Acesso;
import com.devleague.portalnoticias.View.Components.DialogoMsg;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.UUID;
import java.util.regex.Pattern;

/**
 *
 * @author Fnatic
 */
public class ListaAnunciantes extends JFrame {


    /**
     * Creates new form ListaAnunciantes
     */
    public ListaAnunciantes()  {

        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new JDialog();
        jDialog2 = new JDialog();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        listaAnunciantes = new JTable();
        jPanel1 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        nomeAnunciante = new JTextField();
        salarioAnunciante = new JTextField();
        butaoCriarAnunciante = new JButton();
        excluirAnunciante = new JButton();
        logarAnunciante = new JButton();
        jButton1 = new JButton();

        GroupLayout jDialog1Layout = new GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        GroupLayout jDialog2Layout = new GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Selecione o Anunciante para entrar");

        listaAnunciantes.setAutoCreateColumnsFromModel(false);
        listaAnunciantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaAnunciantes);

        jPanel1.setMaximumSize(new Dimension(300, 65000));

        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("Criar Novo Anunciante");

        jLabel3.setText("Nome: ");

        jLabel4.setText("Salario:");

        salarioAnunciante.setToolTipText("");

        butaoCriarAnunciante.setText("Registrar");
        butaoCriarAnunciante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoCriarAnuncianteMouseClicked(evt);
            }
        });

        excluirAnunciante.setText("Excluir Anunciante");
        excluirAnunciante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirAnuncianteMouseClicked(evt);
            }
        });

        logarAnunciante.setText("Logar Anunciante");
        logarAnunciante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logarAnuncianteMouseClicked(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(nomeAnunciante)
                            .addComponent(salarioAnunciante)))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butaoCriarAnunciante))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(excluirAnunciante, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logarAnunciante, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeAnunciante, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salarioAnunciante))
                .addGap(18, 18, 18)
                .addComponent(butaoCriarAnunciante, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(logarAnunciante, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(excluirAnunciante, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("<--");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 532, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoCriarAnuncianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoCriarAnuncianteMouseClicked

        if(nomeAnunciante.getText().length() < 3){
            new DialogoMsg("Nome do Anunciante precisa ter ao menos 3 caracteres");
            return;
        }
        Pattern pattern = Pattern.compile("\\d+.\\d+");

        if(!pattern.matcher(salarioAnunciante.getText()).matches()){
            new DialogoMsg("Salario do anunciante invalido");
            return;
        }
        try{
            Anunciante anunciante = new Anunciante();
            anunciante.setNome(nomeAnunciante.getText());
            if(CreateAnuncianteController.add(anunciante)){
                table();
            }else{
                new DialogoMsg("Não foi possivel Criar o anunciante");
                return;
            }
        }catch (Exception e){
            new DialogoMsg("Salario do anunciante invalido");
            return;
        }





    }//GEN-LAST:event_butaoCriarAnuncianteMouseClicked

    private void excluirAnuncianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirAnuncianteMouseClicked
        try {
            Anunciante anunciante = GetAnuncianteController.get( (UUID) listaAnunciantes.getValueAt(listaAnunciantes.getSelectedRow(), 0));
            if (anunciante != null) {
                if (DeleteAnuncianteController.delete(anunciante)) {
                    table();
                } else {
                    new DialogoMsg("Não foi possivel excluir o anunciante!");
                }
            } else {
                new DialogoMsg("Anunciante não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum Anunciante selecionado!");
        }
    }//GEN-LAST:event_excluirAnuncianteMouseClicked

    private void logarAnuncianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logarAnuncianteMouseClicked
        try {
            Anunciante anunciante = GetAnuncianteController.get((UUID) listaAnunciantes.getValueAt(listaAnunciantes.getSelectedRow(), 0));
            if (anunciante != null) {
                new PageAnunciante(anunciante).setVisible(true);
                this.setVisible(false);

            } else {
                new DialogoMsg("Anunciante não encontrado!");
            }
        }catch (Exception e){
            new DialogoMsg("Nenhum Anunciante selecionado!");
        }
    }//GEN-LAST:event_logarAnuncianteMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new Acesso().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed



    private void table(){

        ArrayList<Anunciante> anunciantes = GetAnuncianteController.getAll();


        ListaAnunciantesTable tm = new ListaAnunciantesTable(anunciantes);


        listaAnunciantes = new JTable(tm);
        listaAnunciantes.getColumnModel().getColumn(0).setPreferredWidth(200);
        jScrollPane1.setViewportView(listaAnunciantes);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton butaoCriarAnunciante;
    private JButton excluirAnunciante;
    private JButton jButton1;
    private JDialog jDialog1;
    private JDialog jDialog2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JPanel jPanel1;
    private JScrollPane jScrollPane1;
    private JTable listaAnunciantes;
    private JButton logarAnunciante;
    private JTextField nomeAnunciante;
    private JTextField salarioAnunciante;
    // End of variables declaration//GEN-END:variables
}
